name: Test
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - run: |
          npm install
      - run: |
          npm run all
  demo:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: ./
        id: demo
        with:
          label-prefix: demo
          pulumi-output: |
            1 to update
      - name: test-outputs
        env:
          JSON: ${{ toJson(steps.demo.outputs) }}
          UPDATE: ${{ steps.demo.outputs.demo-updates }}
        run: |
          echo $JSON
          [ "$UPDATE" == "true" ]
